# State of a battery
Header header       # Header info

string name             # Name of battery
float32 voltage         # Voltage of main battery
float32 current         # Current draw on main battery
float32 stateOfCharge   # State of Charge of main battery
float32 stateOfHealth   # State of Health of main battery
bool isCharging         # Is main battery charging
bool isPlugged          # Is main battery plugged in
string extraInfo        # String for extra info